
// This file has been generated by the GUI designer. Do not modify.
namespace DockingExamples
{
 public partial class LocalizationTest
 {
  private global::Gtk.VBox vbox1;
  private global::Docking.Widgets.LabelLocalized label1;
  private global::Docking.Widgets.ButtonLocalized button1;
  private global::Docking.Widgets.LabelLocalized labellocalized1;

  protected virtual void Build ()
  {
   global::Stetic.Gui.Initialize (this);
   // Widget Examples.LocalizationTest
   global::Stetic.BinContainer.Attach (this);
   this.Name = "Examples.LocalizationTest";
   // Container child Examples.LocalizationTest.Gtk.Container+ContainerChild
   this.vbox1 = new global::Gtk.VBox ();
   this.vbox1.Name = "vbox1";
   this.vbox1.Spacing = 6;
   // Container child vbox1.Gtk.Box+BoxChild
   this.label1 = new global::Docking.Widgets.LabelLocalized ();
   this.label1.Name = "label1";
   this.label1.LabelProp = "Any Content";
   this.vbox1.Add (this.label1);
   global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
   w1.Position = 0;
   w1.Expand = false;
   w1.Fill = false;
   // Container child vbox1.Gtk.Box+BoxChild
   this.button1 = new global::Docking.Widgets.ButtonLocalized ();
   this.button1.CanFocus = true;
   this.button1.Name = "button1";
   this.button1.UseUnderline = true;
   this.button1.Label = "Reset";
   this.vbox1.Add (this.button1);
   global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
   w2.Position = 1;
   w2.Expand = false;
   w2.Fill = false;
   // Container child vbox1.Gtk.Box+BoxChild
   this.labellocalized1 = new global::Docking.Widgets.LabelLocalized ();
   this.labellocalized1.Name = "labellocalized1";
   this.labellocalized1.LabelProp = "Other Content";
   this.vbox1.Add (this.labellocalized1);
   global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labellocalized1]));
   w3.Position = 2;
   w3.Expand = false;
   w3.Fill = false;
   this.Add (this.vbox1);
   if ((this.Child != null)) {
    this.Child.ShowAll ();
   }
   this.Hide ();
  }
 }
}
